import MissionCard from '@/components/MissionCard'
import Head from 'next/head'
import useGetData from '@/hooks/useGetdata'
// api interna
// Cliente / Front
// Servidor / NODEJS

export default function Home () {
  const { data: launches, loading } = useGetData({ url: '/api/getData?limit=100' })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Bienvenidos a next13</h1>
        {/* <MissionCard
          mission_name={data.mission_name}
          links={data.links}
          launch_site={data.launch_site}

        /> */}
        {
          !loading && launches.map(data => {
            return (
              <MissionCard
                key={data.flight_number}
                mission_name={data.mission_name}
                links={data.links}
                launch_site={data.launch_site}
            />
            )
          })
        }
        {
          loading && <h4>Cargando...</h4>
        }
      </main>
    </>
  )
}

// limit peso 8mb
// export async function getStaticProps () {
//   const data = await fetch('http://localhost:3000/api/getData?limit=100')
//     .then(res => res.json())
//     .then(json => json.launches)

//   return {
//     props: {
//       launches: data
//     }
//   }
// }
